notifications:
  email:
    on_success: change
os: linux
language: python
python:
  - "3.8"

services:
  - docker

install:
  - pip install -r requirements.txt

script: 
  - ./loaddata.py

after_script:
  - docker-compose -f ./docker/docker-compose.yml down
