weaviate:
    url: 'http://localhost:8080'
    schema: './schema/schema.json'
    username: "WEAVIATE_USERNAME"
    password: "WEAVIATE_PASSWORD"
    debug: False
    verbose: True
    max_batch_size: 100
    overwrite_schema: true


data:
    taxanomy: "./data/taxanomy/taxanomy.html"
    metadata_dir: "./data/metadata/"

    #metadata_file: "./data/metadata/arxiv-metadata-oai-snapshot.json"
    metadata_file: "https://storage.googleapis.com/semi-technologies-public-data/arxiv-metadata-small.json.zip"
    #metadata_file: "https://storage.googleapis.com/semi-technologies-public-data/arxiv-metadata-oai-snapshot.json.zip"
    #metadata_file: "./data/metadata/10.json"
    #metadata_file: "./data/metadata/100.json"
    #metadata_file: "./data/metadata/1000.json"
    #metadata_file: "./data/metadata/10000.json"
    skip_n_papers: 0
    n_papers: 1000000000
    timeout: 200
    batch_size: 256
