---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '4000'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.4.1
    restart: on-failure:0
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QNA_INFERENCE_API: 'http://qna-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,qna-transformers'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-mpnet-base-v2
    environment:
      ENABLE_CUDA: '1'
      NVIDIA_VISIBLE_DEVICES: 'all'
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: 
            - 'gpu'
  qna-transformers:
    image: semitechnologies/qna-transformers:distilbert-base-uncased-distilled-squad
    environment:
      ENABLE_CUDA: '1'
      NVIDIA_VISIBLE_DEVICES: 'all'
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: 
            - 'gpu'
  enterprise-proxy:
    image: semitechnologies/weaviate-enterprise-usage-collector:0.3.2
    environment:
      - weaviate_enterprise_token=ba09a3f5-3be4-4a56-9b6a-95dce37a640e
      - weaviate_enterprise_project=arXiv-demo-dataset
    links:
      - "weaviate:weaviate.com"
    ports:
      - "8080:8080"
    depends_on:
      - weaviate
...
